<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_Randomchk</name>
   <tag></tag>
   <elementGuidId>341bba17-6d7f-4abf-b79f-1de2fa9b764d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//span[@class='form-checkbox-item']/input)[${index}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[@class='form-checkbox-item']/input)[${index}]</value>
   </webElementProperties>
</WebElementEntity>
