<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_ListValue</name>
   <tag></tag>
   <elementGuidId>811e72ad-f4be-4ee9-a398-15da2f0bdae2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@class='form-checkbox-item']/input[@value='${text}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@class='form-checkbox-item']/input[@value='${text}']</value>
   </webElementProperties>
</WebElementEntity>
