<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_afterhover</name>
   <tag></tag>
   <elementGuidId>d8a1e4a2-4939-41dd-a1dd-2cb25ca8f239</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@aria-describedby=&quot;3val-tooltip&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@aria-describedby=&quot;3val-tooltip&quot;]</value>
   </webElementProperties>
</WebElementEntity>
