<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ifm_adv</name>
   <tag></tag>
   <elementGuidId>107e2edb-9599-41bb-b13a-71ae0befa7eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[contains(@id,'google_ads_iframe')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//iframe[contains(@id,'google_ads_iframe')]</value>
   </webElementProperties>
</WebElementEntity>
