<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>msg_welcome</name>
   <tag></tag>
   <elementGuidId>5df2278d-9246-465a-b104-7664377596c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//marquee[contains(text(),'Welcome')]
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//marquee[contains(text(),'Welcome')]
</value>
   </webElementProperties>
</WebElementEntity>
